import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './NavBar'
import { AuthProvider } from './context/AuthContext'
import { UserProvider } from './context/UserContext'
import { CharacterProvider } from './context/CharacterContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <body className={inter.className}>
            <AuthProvider>
              <UserProvider>
               {/* <CharacterProvider> */}
                <main>
                  <NavBar />
                  {children}
                </main>
               {/* </CharacterProvider> */}
              </UserProvider> 
            </AuthProvider>
          </body>
    </html>
  )
}
